# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\uic_files\download.ui'
#
# Created: Mon Aug 26 11:48:38 2013
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_DownloadDialog(object):
    def setupUi(self, DownloadDialog):
        DownloadDialog.setObjectName("DownloadDialog")
        DownloadDialog.resize(380, 115)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(DownloadDialog.sizePolicy().hasHeightForWidth())
        DownloadDialog.setSizePolicy(sizePolicy)
        DownloadDialog.setMinimumSize(QtCore.QSize(0, 0))
        DownloadDialog.setMaximumSize(QtCore.QSize(380, 115))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/app_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        DownloadDialog.setWindowIcon(icon)
        self.verticalLayout = QtGui.QVBoxLayout(DownloadDialog)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSpacing(4)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.totalSizeLbl_st = QtGui.QLabel(DownloadDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.totalSizeLbl_st.sizePolicy().hasHeightForWidth())
        self.totalSizeLbl_st.setSizePolicy(sizePolicy)
        self.totalSizeLbl_st.setObjectName("totalSizeLbl_st")
        self.horizontalLayout.addWidget(self.totalSizeLbl_st)
        self.totalSizeLbl = QtGui.QLabel(DownloadDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.totalSizeLbl.sizePolicy().hasHeightForWidth())
        self.totalSizeLbl.setSizePolicy(sizePolicy)
        self.totalSizeLbl.setObjectName("totalSizeLbl")
        self.horizontalLayout.addWidget(self.totalSizeLbl)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(4)
        self.horizontalLayout_2.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.downloadedLbl_st = QtGui.QLabel(DownloadDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.downloadedLbl_st.sizePolicy().hasHeightForWidth())
        self.downloadedLbl_st.setSizePolicy(sizePolicy)
        self.downloadedLbl_st.setObjectName("downloadedLbl_st")
        self.horizontalLayout_2.addWidget(self.downloadedLbl_st)
        self.downloadedLbl = QtGui.QLabel(DownloadDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.downloadedLbl.sizePolicy().hasHeightForWidth())
        self.downloadedLbl.setSizePolicy(sizePolicy)
        self.downloadedLbl.setObjectName("downloadedLbl")
        self.horizontalLayout_2.addWidget(self.downloadedLbl)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem = QtGui.QSpacerItem(20, 9, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem)
        self.progressBar = QtGui.QProgressBar(DownloadDialog)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setTextDirection(QtGui.QProgressBar.TopToBottom)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, 9, -1, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.buttonBox = QtGui.QDialogButtonBox(DownloadDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout_4.addWidget(self.buttonBox)
        self.verticalLayout.addLayout(self.horizontalLayout_4)

        self.retranslateUi(DownloadDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), DownloadDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), DownloadDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(DownloadDialog)

    def retranslateUi(self, DownloadDialog):
        DownloadDialog.setWindowTitle(QtGui.QApplication.translate("DownloadDialog", "Downloading file...", None, QtGui.QApplication.UnicodeUTF8))
        self.totalSizeLbl_st.setText(QtGui.QApplication.translate("DownloadDialog", "Total size:", None, QtGui.QApplication.UnicodeUTF8))
        self.totalSizeLbl.setText(QtGui.QApplication.translate("DownloadDialog", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.downloadedLbl_st.setText(QtGui.QApplication.translate("DownloadDialog", "Downloaded:", None, QtGui.QApplication.UnicodeUTF8))
        self.downloadedLbl.setText(QtGui.QApplication.translate("DownloadDialog", "0", None, QtGui.QApplication.UnicodeUTF8))

import icons_rc
