# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\uic_files\login.ui'
#
# Created: Tue Sep 17 15:10:25 2013
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_LoginForm(object):
    def setupUi(self, LoginForm):
        LoginForm.setObjectName("LoginForm")
        LoginForm.resize(460, 185)
        LoginForm.setBaseSize(QtCore.QSize(0, 0))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/app_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        LoginForm.setWindowIcon(icon)
        LoginForm.setSizeGripEnabled(False)
        self.verticalLayout = QtGui.QVBoxLayout(LoginForm)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.connectIcon = QtGui.QLabel(LoginForm)
        self.connectIcon.setText("")
        self.connectIcon.setPixmap(QtGui.QPixmap(":/icons/icons/conect22.png"))
        self.connectIcon.setObjectName("connectIcon")
        self.horizontalLayout_2.addWidget(self.connectIcon)
        self.headerLbl = QtGui.QLabel(LoginForm)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.headerLbl.sizePolicy().hasHeightForWidth())
        self.headerLbl.setSizePolicy(sizePolicy)
        self.headerLbl.setObjectName("headerLbl")
        self.horizontalLayout_2.addWidget(self.headerLbl)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.line = QtGui.QFrame(LoginForm)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.serverLbl = QtGui.QLabel(LoginForm)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.serverLbl.sizePolicy().hasHeightForWidth())
        self.serverLbl.setSizePolicy(sizePolicy)
        self.serverLbl.setObjectName("serverLbl")
        self.gridLayout.addWidget(self.serverLbl, 0, 0, 1, 1)
        self.serverEdit = QtGui.QLineEdit(LoginForm)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.serverEdit.sizePolicy().hasHeightForWidth())
        self.serverEdit.setSizePolicy(sizePolicy)
        self.serverEdit.setObjectName("serverEdit")
        self.gridLayout.addWidget(self.serverEdit, 0, 1, 1, 1)
        self.usernameLbl = QtGui.QLabel(LoginForm)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.usernameLbl.sizePolicy().hasHeightForWidth())
        self.usernameLbl.setSizePolicy(sizePolicy)
        self.usernameLbl.setObjectName("usernameLbl")
        self.gridLayout.addWidget(self.usernameLbl, 1, 0, 1, 1)
        self.usernameEdit = QtGui.QLineEdit(LoginForm)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.usernameEdit.sizePolicy().hasHeightForWidth())
        self.usernameEdit.setSizePolicy(sizePolicy)
        self.usernameEdit.setPlaceholderText("")
        self.usernameEdit.setObjectName("usernameEdit")
        self.gridLayout.addWidget(self.usernameEdit, 1, 1, 1, 1)
        self.passwordLbl = QtGui.QLabel(LoginForm)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.passwordLbl.sizePolicy().hasHeightForWidth())
        self.passwordLbl.setSizePolicy(sizePolicy)
        self.passwordLbl.setObjectName("passwordLbl")
        self.gridLayout.addWidget(self.passwordLbl, 2, 0, 1, 1)
        self.passwordEdit = QtGui.QLineEdit(LoginForm)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.passwordEdit.sizePolicy().hasHeightForWidth())
        self.passwordEdit.setSizePolicy(sizePolicy)
        self.passwordEdit.setEchoMode(QtGui.QLineEdit.Password)
        self.passwordEdit.setPlaceholderText("")
        self.passwordEdit.setObjectName("passwordEdit")
        self.gridLayout.addWidget(self.passwordEdit, 2, 1, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.infoIcon = QtGui.QLabel(LoginForm)
        self.infoIcon.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.infoIcon.sizePolicy().hasHeightForWidth())
        self.infoIcon.setSizePolicy(sizePolicy)
        self.infoIcon.setMinimumSize(QtCore.QSize(0, 0))
        self.infoIcon.setMaximumSize(QtCore.QSize(32, 32))
        self.infoIcon.setBaseSize(QtCore.QSize(0, 0))
        self.infoIcon.setText("")
        self.infoIcon.setPixmap(QtGui.QPixmap(":/icons/icons/info16.png"))
        self.infoIcon.setObjectName("infoIcon")
        self.horizontalLayout.addWidget(self.infoIcon)
        self.warningLbl = QtGui.QLabel(LoginForm)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.warningLbl.sizePolicy().hasHeightForWidth())
        self.warningLbl.setSizePolicy(sizePolicy)
        self.warningLbl.setObjectName("warningLbl")
        self.horizontalLayout.addWidget(self.warningLbl)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.horizontalLayout.addItem(spacerItem)
        self.gridLayout.addLayout(self.horizontalLayout, 3, 1, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(LoginForm)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        self.buttonBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 4, 0, 1, 2)
        self.verticalLayout.addLayout(self.gridLayout)

        self.retranslateUi(LoginForm)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), LoginForm.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), LoginForm.reject)
        QtCore.QMetaObject.connectSlotsByName(LoginForm)

    def retranslateUi(self, LoginForm):
        LoginForm.setWindowTitle(QtGui.QApplication.translate("LoginForm", "Tovian - User login", None, QtGui.QApplication.UnicodeUTF8))
        self.headerLbl.setText(QtGui.QApplication.translate("LoginForm", "Enter server adress and login information:", None, QtGui.QApplication.UnicodeUTF8))
        self.serverLbl.setText(QtGui.QApplication.translate("LoginForm", "Server:", None, QtGui.QApplication.UnicodeUTF8))
        self.serverEdit.setText(QtGui.QApplication.translate("LoginForm", "http://127.0.0.1", None, QtGui.QApplication.UnicodeUTF8))
        self.usernameLbl.setText(QtGui.QApplication.translate("LoginForm", "Username:", None, QtGui.QApplication.UnicodeUTF8))
        self.passwordLbl.setText(QtGui.QApplication.translate("LoginForm", "Password:", None, QtGui.QApplication.UnicodeUTF8))
        self.warningLbl.setText(QtGui.QApplication.translate("LoginForm", "Information", None, QtGui.QApplication.UnicodeUTF8))

import icons_rc
import icons_rc
