# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uic_files/main-ui.ui'
#
# Created: Mon Mar 10 11:16:39 2014
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1140, 692)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/app_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.nameZoomHLayout = QtGui.QHBoxLayout()
        self.nameZoomHLayout.setObjectName("nameZoomHLayout")
        self.nameLbl = QtGui.QLabel(self.centralwidget)
        self.nameLbl.setObjectName("nameLbl")
        self.nameZoomHLayout.addWidget(self.nameLbl)
        self.videoNameLlb = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.videoNameLlb.sizePolicy().hasHeightForWidth())
        self.videoNameLlb.setSizePolicy(sizePolicy)
        self.videoNameLlb.setObjectName("videoNameLlb")
        self.nameZoomHLayout.addWidget(self.videoNameLlb)
        self.zoomLbl = QtGui.QLabel(self.centralwidget)
        self.zoomLbl.setStatusTip("")
        self.zoomLbl.setObjectName("zoomLbl")
        self.nameZoomHLayout.addWidget(self.zoomLbl)
        self.zoomlSlider = QtGui.QSlider(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zoomlSlider.sizePolicy().hasHeightForWidth())
        self.zoomlSlider.setSizePolicy(sizePolicy)
        self.zoomlSlider.setMinimumSize(QtCore.QSize(0, 0))
        self.zoomlSlider.setBaseSize(QtCore.QSize(0, 0))
        self.zoomlSlider.setStatusTip("")
        self.zoomlSlider.setMinimum(100)
        self.zoomlSlider.setMaximum(600)
        self.zoomlSlider.setSingleStep(10)
        self.zoomlSlider.setOrientation(QtCore.Qt.Horizontal)
        self.zoomlSlider.setObjectName("zoomlSlider")
        self.nameZoomHLayout.addWidget(self.zoomlSlider)
        self.zoomValueLbl = QtGui.QLabel(self.centralwidget)
        self.zoomValueLbl.setStatusTip("")
        self.zoomValueLbl.setObjectName("zoomValueLbl")
        self.nameZoomHLayout.addWidget(self.zoomValueLbl)
        self.gridLayout.addLayout(self.nameZoomHLayout, 0, 0, 1, 1)
        self.userHLayout = QtGui.QHBoxLayout()
        self.userHLayout.setObjectName("userHLayout")
        self.userLbl = QtGui.QLabel(self.centralwidget)
        self.userLbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.userLbl.setObjectName("userLbl")
        self.userHLayout.addWidget(self.userLbl)
        self.gridLayout.addLayout(self.userHLayout, 0, 1, 1, 1)
        self.videoGridLayout = QtGui.QGridLayout()
        self.videoGridLayout.setObjectName("videoGridLayout")
        self.graphicsView = QtGui.QGraphicsView(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsView.sizePolicy().hasHeightForWidth())
        self.graphicsView.setSizePolicy(sizePolicy)
        self.graphicsView.setMinimumSize(QtCore.QSize(0, 0))
        self.graphicsView.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.graphicsView.setAutoFillBackground(True)
        self.graphicsView.setObjectName("graphicsView")
        self.videoGridLayout.addWidget(self.graphicsView, 0, 0, 1, 1)
        self.nonVisTable = QtGui.QTableWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nonVisTable.sizePolicy().hasHeightForWidth())
        self.nonVisTable.setSizePolicy(sizePolicy)
        self.nonVisTable.setMaximumSize(QtCore.QSize(16777215, 120))
        self.nonVisTable.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.nonVisTable.setTabKeyNavigation(False)
        self.nonVisTable.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.nonVisTable.setSelectionBehavior(QtGui.QAbstractItemView.SelectItems)
        self.nonVisTable.setShowGrid(True)
        self.nonVisTable.setWordWrap(False)
        self.nonVisTable.setRowCount(0)
        self.nonVisTable.setColumnCount(0)
        self.nonVisTable.setObjectName("nonVisTable")
        self.nonVisTable.setColumnCount(0)
        self.nonVisTable.setRowCount(0)
        self.nonVisTable.horizontalHeader().setDefaultSectionSize(30)
        self.nonVisTable.verticalHeader().setVisible(False)
        self.nonVisTable.verticalHeader().setDefaultSectionSize(19)
        self.videoGridLayout.addWidget(self.nonVisTable, 1, 0, 1, 1)
        self.gridLayout.addLayout(self.videoGridLayout, 1, 0, 1, 1)
        self.rightSplitter = QtGui.QSplitter(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.rightSplitter.sizePolicy().hasHeightForWidth())
        self.rightSplitter.setSizePolicy(sizePolicy)
        self.rightSplitter.setMinimumSize(QtCore.QSize(360, 0))
        self.rightSplitter.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.rightSplitter.setOrientation(QtCore.Qt.Vertical)
        self.rightSplitter.setHandleWidth(6)
        self.rightSplitter.setObjectName("rightSplitter")
        self.toolsAndVideoTabWidget = QtGui.QTabWidget(self.rightSplitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.toolsAndVideoTabWidget.sizePolicy().hasHeightForWidth())
        self.toolsAndVideoTabWidget.setSizePolicy(sizePolicy)
        self.toolsAndVideoTabWidget.setMinimumSize(QtCore.QSize(0, 115))
        self.toolsAndVideoTabWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.toolsAndVideoTabWidget.setBaseSize(QtCore.QSize(0, 0))
        self.toolsAndVideoTabWidget.setStatusTip("")
        self.toolsAndVideoTabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.toolsAndVideoTabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.toolsAndVideoTabWidget.setTabsClosable(False)
        self.toolsAndVideoTabWidget.setObjectName("toolsAndVideoTabWidget")
        self.toolsTab = QtGui.QWidget()
        self.toolsTab.setObjectName("toolsTab")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.toolsTab)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setContentsMargins(10, 20, 10, 10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.rectToolBtn = QtGui.QPushButton(self.toolsTab)
        self.rectToolBtn.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rectToolBtn.sizePolicy().hasHeightForWidth())
        self.rectToolBtn.setSizePolicy(sizePolicy)
        self.rectToolBtn.setMinimumSize(QtCore.QSize(50, 50))
        self.rectToolBtn.setMaximumSize(QtCore.QSize(50, 50))
        self.rectToolBtn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/rectangle.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rectToolBtn.setIcon(icon1)
        self.rectToolBtn.setIconSize(QtCore.QSize(24, 24))
        self.rectToolBtn.setObjectName("rectToolBtn")
        self.horizontalLayout.addWidget(self.rectToolBtn)
        self.circleToolBtn = QtGui.QPushButton(self.toolsTab)
        self.circleToolBtn.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.circleToolBtn.sizePolicy().hasHeightForWidth())
        self.circleToolBtn.setSizePolicy(sizePolicy)
        self.circleToolBtn.setMinimumSize(QtCore.QSize(50, 50))
        self.circleToolBtn.setMaximumSize(QtCore.QSize(50, 50))
        self.circleToolBtn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/circle.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.circleToolBtn.setIcon(icon2)
        self.circleToolBtn.setIconSize(QtCore.QSize(24, 24))
        self.circleToolBtn.setObjectName("circleToolBtn")
        self.horizontalLayout.addWidget(self.circleToolBtn)
        self.ellipseToolBtn = QtGui.QPushButton(self.toolsTab)
        self.ellipseToolBtn.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ellipseToolBtn.sizePolicy().hasHeightForWidth())
        self.ellipseToolBtn.setSizePolicy(sizePolicy)
        self.ellipseToolBtn.setMinimumSize(QtCore.QSize(50, 50))
        self.ellipseToolBtn.setMaximumSize(QtCore.QSize(50, 50))
        self.ellipseToolBtn.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/ellipse.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ellipseToolBtn.setIcon(icon3)
        self.ellipseToolBtn.setIconSize(QtCore.QSize(24, 24))
        self.ellipseToolBtn.setObjectName("ellipseToolBtn")
        self.horizontalLayout.addWidget(self.ellipseToolBtn)
        self.pointToolBtn = QtGui.QPushButton(self.toolsTab)
        self.pointToolBtn.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pointToolBtn.sizePolicy().hasHeightForWidth())
        self.pointToolBtn.setSizePolicy(sizePolicy)
        self.pointToolBtn.setMinimumSize(QtCore.QSize(50, 50))
        self.pointToolBtn.setMaximumSize(QtCore.QSize(50, 50))
        self.pointToolBtn.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/icons/point.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pointToolBtn.setIcon(icon4)
        self.pointToolBtn.setIconSize(QtCore.QSize(16, 16))
        self.pointToolBtn.setObjectName("pointToolBtn")
        self.horizontalLayout.addWidget(self.pointToolBtn)
        self.nonVisToolBtn = QtGui.QPushButton(self.toolsTab)
        self.nonVisToolBtn.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nonVisToolBtn.sizePolicy().hasHeightForWidth())
        self.nonVisToolBtn.setSizePolicy(sizePolicy)
        self.nonVisToolBtn.setMinimumSize(QtCore.QSize(50, 50))
        self.nonVisToolBtn.setMaximumSize(QtCore.QSize(50, 50))
        self.nonVisToolBtn.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/icons/nonvisual.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.nonVisToolBtn.setIcon(icon5)
        self.nonVisToolBtn.setIconSize(QtCore.QSize(32, 32))
        self.nonVisToolBtn.setObjectName("nonVisToolBtn")
        self.horizontalLayout.addWidget(self.nonVisToolBtn)
        self.maskToolBtn = QtGui.QPushButton(self.toolsTab)
        self.maskToolBtn.setMinimumSize(QtCore.QSize(50, 50))
        self.maskToolBtn.setMaximumSize(QtCore.QSize(50, 50))
        self.maskToolBtn.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/icons/mask.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.maskToolBtn.setIcon(icon6)
        self.maskToolBtn.setIconSize(QtCore.QSize(24, 24))
        self.maskToolBtn.setObjectName("maskToolBtn")
        self.horizontalLayout.addWidget(self.maskToolBtn)
        spacerItem = QtGui.QSpacerItem(0, 10, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        spacerItem1 = QtGui.QSpacerItem(20, 1, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.toolsAndVideoTabWidget.addTab(self.toolsTab, "")
        self.annotationsTab = QtGui.QWidget()
        self.annotationsTab.setObjectName("annotationsTab")
        self.verticalLayout = QtGui.QVBoxLayout(self.annotationsTab)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.annotationsTable = QtGui.QTableWidget(self.annotationsTab)
        self.annotationsTable.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.annotationsTable.setTabKeyNavigation(False)
        self.annotationsTable.setAlternatingRowColors(True)
        self.annotationsTable.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.annotationsTable.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.annotationsTable.setRowCount(3)
        self.annotationsTable.setObjectName("annotationsTable")
        self.annotationsTable.setColumnCount(3)
        self.annotationsTable.setRowCount(3)
        item = QtGui.QTableWidgetItem()
        self.annotationsTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.annotationsTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.annotationsTable.setHorizontalHeaderItem(2, item)
        self.annotationsTable.horizontalHeader().setDefaultSectionSize(100)
        self.annotationsTable.horizontalHeader().setMinimumSectionSize(26)
        self.annotationsTable.horizontalHeader().setStretchLastSection(False)
        self.annotationsTable.verticalHeader().setVisible(False)
        self.annotationsTable.verticalHeader().setDefaultSectionSize(20)
        self.annotationsTable.verticalHeader().setHighlightSections(True)
        self.verticalLayout.addWidget(self.annotationsTable)
        self.toolsAndVideoTabWidget.addTab(self.annotationsTab, "")
        self.videoTab = QtGui.QWidget()
        self.videoTab.setObjectName("videoTab")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.videoTab)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.videoTable = QtGui.QTableWidget(self.videoTab)
        self.videoTable.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.videoTable.setTabKeyNavigation(False)
        self.videoTable.setAlternatingRowColors(True)
        self.videoTable.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.videoTable.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.videoTable.setGridStyle(QtCore.Qt.DotLine)
        self.videoTable.setRowCount(6)
        self.videoTable.setColumnCount(2)
        self.videoTable.setObjectName("videoTable")
        self.videoTable.setColumnCount(2)
        self.videoTable.setRowCount(6)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.videoTable.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.videoTable.setItem(1, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.videoTable.setItem(2, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.videoTable.setItem(3, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.videoTable.setItem(4, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.NoItemFlags)
        self.videoTable.setItem(5, 0, item)
        self.videoTable.horizontalHeader().setVisible(False)
        self.videoTable.horizontalHeader().setDefaultSectionSize(80)
        self.videoTable.horizontalHeader().setStretchLastSection(True)
        self.videoTable.verticalHeader().setVisible(False)
        self.videoTable.verticalHeader().setDefaultSectionSize(20)
        self.videoTable.verticalHeader().setStretchLastSection(False)
        self.horizontalLayout_4.addWidget(self.videoTable)
        self.toolsAndVideoTabWidget.addTab(self.videoTab, "")
        self.attributesContainerFrame = QtGui.QFrame(self.rightSplitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.attributesContainerFrame.sizePolicy().hasHeightForWidth())
        self.attributesContainerFrame.setSizePolicy(sizePolicy)
        self.attributesContainerFrame.setFrameShape(QtGui.QFrame.NoFrame)
        self.attributesContainerFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.attributesContainerFrame.setObjectName("attributesContainerFrame")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.attributesContainerFrame)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.annotAttributesLbl = QtGui.QLabel(self.attributesContainerFrame)
        self.annotAttributesLbl.setObjectName("annotAttributesLbl")
        self.verticalLayout_3.addWidget(self.annotAttributesLbl)
        self.attributesSplitter = QtGui.QSplitter(self.attributesContainerFrame)
        self.attributesSplitter.setOrientation(QtCore.Qt.Vertical)
        self.attributesSplitter.setHandleWidth(1)
        self.attributesSplitter.setObjectName("attributesSplitter")
        self.globalTable = QtGui.QTableWidget(self.attributesSplitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.globalTable.sizePolicy().hasHeightForWidth())
        self.globalTable.setSizePolicy(sizePolicy)
        self.globalTable.setTabKeyNavigation(False)
        self.globalTable.setAlternatingRowColors(True)
        self.globalTable.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.globalTable.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.globalTable.setRowCount(0)
        self.globalTable.setColumnCount(2)
        self.globalTable.setObjectName("globalTable")
        self.globalTable.setColumnCount(2)
        self.globalTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.globalTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.globalTable.setHorizontalHeaderItem(1, item)
        self.globalTable.horizontalHeader().setCascadingSectionResizes(False)
        self.globalTable.horizontalHeader().setDefaultSectionSize(150)
        self.globalTable.horizontalHeader().setStretchLastSection(True)
        self.globalTable.verticalHeader().setVisible(False)
        self.globalTable.verticalHeader().setDefaultSectionSize(20)
        self.localTable = QtGui.QTableWidget(self.attributesSplitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.localTable.sizePolicy().hasHeightForWidth())
        self.localTable.setSizePolicy(sizePolicy)
        self.localTable.setTabKeyNavigation(False)
        self.localTable.setAlternatingRowColors(True)
        self.localTable.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.localTable.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.localTable.setRowCount(0)
        self.localTable.setColumnCount(2)
        self.localTable.setObjectName("localTable")
        self.localTable.setColumnCount(2)
        self.localTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.localTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.localTable.setHorizontalHeaderItem(1, item)
        self.localTable.horizontalHeader().setDefaultSectionSize(150)
        self.localTable.horizontalHeader().setMinimumSectionSize(26)
        self.localTable.horizontalHeader().setStretchLastSection(True)
        self.localTable.verticalHeader().setVisible(False)
        self.localTable.verticalHeader().setDefaultSectionSize(20)
        self.verticalLayout_3.addWidget(self.attributesSplitter)
        self.gridLayout.addWidget(self.rightSplitter, 1, 1, 1, 1)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.mainVideoBarHLayout = QtGui.QHBoxLayout()
        self.mainVideoBarHLayout.setObjectName("mainVideoBarHLayout")
        self.skipLeftBtn = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.skipLeftBtn.sizePolicy().hasHeightForWidth())
        self.skipLeftBtn.setSizePolicy(sizePolicy)
        self.skipLeftBtn.setMinimumSize(QtCore.QSize(0, 30))
        self.skipLeftBtn.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/icons/media-fast-backward.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.skipLeftBtn.setIcon(icon7)
        self.skipLeftBtn.setIconSize(QtCore.QSize(16, 16))
        self.skipLeftBtn.setFlat(True)
        self.skipLeftBtn.setObjectName("skipLeftBtn")
        self.mainVideoBarHLayout.addWidget(self.skipLeftBtn)
        self.skipSecBackBtn = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.skipSecBackBtn.sizePolicy().hasHeightForWidth())
        self.skipSecBackBtn.setSizePolicy(sizePolicy)
        self.skipSecBackBtn.setMinimumSize(QtCore.QSize(0, 30))
        self.skipSecBackBtn.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/icons/jump_sec_backward.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.skipSecBackBtn.setIcon(icon8)
        self.skipSecBackBtn.setIconSize(QtCore.QSize(24, 16))
        self.skipSecBackBtn.setFlat(True)
        self.skipSecBackBtn.setObjectName("skipSecBackBtn")
        self.mainVideoBarHLayout.addWidget(self.skipSecBackBtn)
        self.frameLeftBtn = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameLeftBtn.sizePolicy().hasHeightForWidth())
        self.frameLeftBtn.setSizePolicy(sizePolicy)
        self.frameLeftBtn.setMinimumSize(QtCore.QSize(0, 30))
        self.frameLeftBtn.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/icons/media-previous.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.frameLeftBtn.setIcon(icon9)
        self.frameLeftBtn.setIconSize(QtCore.QSize(16, 16))
        self.frameLeftBtn.setFlat(True)
        self.frameLeftBtn.setObjectName("frameLeftBtn")
        self.mainVideoBarHLayout.addWidget(self.frameLeftBtn)
        self.playPauseBtn = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.playPauseBtn.sizePolicy().hasHeightForWidth())
        self.playPauseBtn.setSizePolicy(sizePolicy)
        self.playPauseBtn.setMinimumSize(QtCore.QSize(0, 30))
        self.playPauseBtn.setCursor(QtCore.Qt.PointingHandCursor)
        self.playPauseBtn.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icons/icons/media-play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.playPauseBtn.setIcon(icon10)
        self.playPauseBtn.setIconSize(QtCore.QSize(24, 24))
        self.playPauseBtn.setObjectName("playPauseBtn")
        self.mainVideoBarHLayout.addWidget(self.playPauseBtn)
        self.stopBtn = QtGui.QPushButton(self.centralwidget)
        self.stopBtn.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stopBtn.sizePolicy().hasHeightForWidth())
        self.stopBtn.setSizePolicy(sizePolicy)
        self.stopBtn.setMinimumSize(QtCore.QSize(0, 30))
        self.stopBtn.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/icons/icons/media-stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stopBtn.setIcon(icon11)
        self.stopBtn.setIconSize(QtCore.QSize(24, 24))
        self.stopBtn.setObjectName("stopBtn")
        self.mainVideoBarHLayout.addWidget(self.stopBtn)
        self.frameRightBtn = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameRightBtn.sizePolicy().hasHeightForWidth())
        self.frameRightBtn.setSizePolicy(sizePolicy)
        self.frameRightBtn.setMinimumSize(QtCore.QSize(0, 30))
        self.frameRightBtn.setText("")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/icons/icons/media-next.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.frameRightBtn.setIcon(icon12)
        self.frameRightBtn.setIconSize(QtCore.QSize(16, 16))
        self.frameRightBtn.setFlat(True)
        self.frameRightBtn.setObjectName("frameRightBtn")
        self.mainVideoBarHLayout.addWidget(self.frameRightBtn)
        self.skipSecFwdBtn = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.skipSecFwdBtn.sizePolicy().hasHeightForWidth())
        self.skipSecFwdBtn.setSizePolicy(sizePolicy)
        self.skipSecFwdBtn.setMinimumSize(QtCore.QSize(0, 30))
        self.skipSecFwdBtn.setText("")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/icons/icons/jump_sec_forward.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.skipSecFwdBtn.setIcon(icon13)
        self.skipSecFwdBtn.setIconSize(QtCore.QSize(24, 16))
        self.skipSecFwdBtn.setFlat(True)
        self.skipSecFwdBtn.setObjectName("skipSecFwdBtn")
        self.mainVideoBarHLayout.addWidget(self.skipSecFwdBtn)
        self.skipRightBtn = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.skipRightBtn.sizePolicy().hasHeightForWidth())
        self.skipRightBtn.setSizePolicy(sizePolicy)
        self.skipRightBtn.setMinimumSize(QtCore.QSize(0, 30))
        self.skipRightBtn.setText("")
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/icons/icons/media-fast-forward.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.skipRightBtn.setIcon(icon14)
        self.skipRightBtn.setIconSize(QtCore.QSize(16, 16))
        self.skipRightBtn.setFlat(True)
        self.skipRightBtn.setObjectName("skipRightBtn")
        self.mainVideoBarHLayout.addWidget(self.skipRightBtn)
        self.timeLbl = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timeLbl.sizePolicy().hasHeightForWidth())
        self.timeLbl.setSizePolicy(sizePolicy)
        self.timeLbl.setMinimumSize(QtCore.QSize(0, 0))
        self.timeLbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.timeLbl.setObjectName("timeLbl")
        self.mainVideoBarHLayout.addWidget(self.timeLbl)
        self.verticalLayout_5.addLayout(self.mainVideoBarHLayout)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.perFrameSlider = QtGui.QSlider(self.centralwidget)
        self.perFrameSlider.setEnabled(False)
        self.perFrameSlider.setMinimum(-50)
        self.perFrameSlider.setMaximum(50)
        self.perFrameSlider.setProperty("value", 0)
        self.perFrameSlider.setSliderPosition(0)
        self.perFrameSlider.setTracking(True)
        self.perFrameSlider.setOrientation(QtCore.Qt.Horizontal)
        self.perFrameSlider.setTickPosition(QtGui.QSlider.TicksBothSides)
        self.perFrameSlider.setObjectName("perFrameSlider")
        self.horizontalLayout_3.addWidget(self.perFrameSlider)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.gridLayout.addLayout(self.verticalLayout_5, 2, 0, 1, 1)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtGui.QSpacerItem(70, 0, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.undoBtn = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.undoBtn.sizePolicy().hasHeightForWidth())
        self.undoBtn.setSizePolicy(sizePolicy)
        self.undoBtn.setMaximumSize(QtCore.QSize(24, 16777215))
        self.undoBtn.setCursor(QtCore.Qt.PointingHandCursor)
        self.undoBtn.setText("")
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/icons/icons/undo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.undoBtn.setIcon(icon15)
        self.undoBtn.setIconSize(QtCore.QSize(16, 16))
        self.undoBtn.setFlat(True)
        self.undoBtn.setObjectName("undoBtn")
        self.horizontalLayout_2.addWidget(self.undoBtn)
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setFrameShadow(QtGui.QFrame.Raised)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_2.addWidget(self.line)
        self.commitBtn = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.commitBtn.sizePolicy().hasHeightForWidth())
        self.commitBtn.setSizePolicy(sizePolicy)
        self.commitBtn.setMinimumSize(QtCore.QSize(0, 0))
        self.commitBtn.setSizeIncrement(QtCore.QSize(0, 0))
        self.commitBtn.setBaseSize(QtCore.QSize(0, 0))
        self.commitBtn.setCursor(QtCore.Qt.PointingHandCursor)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(":/icons/icons/commit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.commitBtn.setIcon(icon16)
        self.commitBtn.setIconSize(QtCore.QSize(24, 24))
        self.commitBtn.setDefault(False)
        self.commitBtn.setFlat(True)
        self.commitBtn.setObjectName("commitBtn")
        self.horizontalLayout_2.addWidget(self.commitBtn)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.gridLayout.addLayout(self.verticalLayout_2, 2, 1, 1, 1)
        self.gridLayout.setColumnStretch(0, 10)
        self.gridLayout.setColumnStretch(1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1140, 23))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuTools = QtGui.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuFont_size = QtGui.QMenu(self.menuView)
        self.menuFont_size.setObjectName("menuFont_size")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setSizeGripEnabled(False)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionClose = QtGui.QAction(MainWindow)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(":/icons/icons/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionClose.setIcon(icon17)
        self.actionClose.setObjectName("actionClose")
        self.actionAbout = QtGui.QAction(MainWindow)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(":/icons/icons/about.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbout.setIcon(icon18)
        self.actionAbout.setObjectName("actionAbout")
        self.actionUndo_changes = QtGui.QAction(MainWindow)
        self.actionUndo_changes.setIcon(icon15)
        self.actionUndo_changes.setObjectName("actionUndo_changes")
        self.actionCommit = QtGui.QAction(MainWindow)
        self.actionCommit.setIcon(icon16)
        self.actionCommit.setObjectName("actionCommit")
        self.actionDelete = QtGui.QAction(MainWindow)
        self.actionDelete.setEnabled(False)
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap(":/icons/icons/delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDelete.setIcon(icon19)
        self.actionDelete.setObjectName("actionDelete")
        self.actionTake_a_snapshot = QtGui.QAction(MainWindow)
        self.actionTake_a_snapshot.setObjectName("actionTake_a_snapshot")
        self.actionFit_to_video = QtGui.QAction(MainWindow)
        self.actionFit_to_video.setObjectName("actionFit_to_video")
        self.actionFontSmall = QtGui.QAction(MainWindow)
        self.actionFontSmall.setObjectName("actionFontSmall")
        self.actionFontNormal = QtGui.QAction(MainWindow)
        self.actionFontNormal.setObjectName("actionFontNormal")
        self.actionFontLarge = QtGui.QAction(MainWindow)
        self.actionFontLarge.setObjectName("actionFontLarge")
        self.actionFontNone = QtGui.QAction(MainWindow)
        self.actionFontNone.setObjectName("actionFontNone")
        self.actionKeyboard_shortcuts = QtGui.QAction(MainWindow)
        self.actionKeyboard_shortcuts.setObjectName("actionKeyboard_shortcuts")
        self.actionGo_to = QtGui.QAction(MainWindow)
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap(":/icons/icons/goto.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionGo_to.setIcon(icon20)
        self.actionGo_to.setObjectName("actionGo_to")
        self.actionMark_current_frame = QtGui.QAction(MainWindow)
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap(":/icons/icons/mark.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionMark_current_frame.setIcon(icon21)
        self.actionMark_current_frame.setObjectName("actionMark_current_frame")
        self.menuFile.addAction(self.actionCommit)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionClose)
        self.menuTools.addAction(self.actionUndo_changes)
        self.menuTools.addSeparator()
        self.menuTools.addAction(self.actionDelete)
        self.menuHelp.addAction(self.actionKeyboard_shortcuts)
        self.menuHelp.addAction(self.actionAbout)
        self.menuFont_size.addAction(self.actionFontSmall)
        self.menuFont_size.addAction(self.actionFontNormal)
        self.menuFont_size.addAction(self.actionFontLarge)
        self.menuFont_size.addAction(self.actionFontNone)
        self.menuView.addAction(self.actionGo_to)
        self.menuView.addAction(self.actionMark_current_frame)
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionFit_to_video)
        self.menuView.addAction(self.menuFont_size.menuAction())
        self.menuView.addAction(self.actionTake_a_snapshot)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.toolsAndVideoTabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.actionClose, QtCore.SIGNAL("triggered()"), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.playPauseBtn, self.stopBtn)
        MainWindow.setTabOrder(self.stopBtn, self.perFrameSlider)
        MainWindow.setTabOrder(self.perFrameSlider, self.toolsAndVideoTabWidget)
        MainWindow.setTabOrder(self.toolsAndVideoTabWidget, self.globalTable)
        MainWindow.setTabOrder(self.globalTable, self.localTable)
        MainWindow.setTabOrder(self.localTable, self.zoomlSlider)
        MainWindow.setTabOrder(self.zoomlSlider, self.graphicsView)
        MainWindow.setTabOrder(self.graphicsView, self.rectToolBtn)
        MainWindow.setTabOrder(self.rectToolBtn, self.circleToolBtn)
        MainWindow.setTabOrder(self.circleToolBtn, self.ellipseToolBtn)
        MainWindow.setTabOrder(self.ellipseToolBtn, self.pointToolBtn)
        MainWindow.setTabOrder(self.pointToolBtn, self.annotationsTable)
        MainWindow.setTabOrder(self.annotationsTable, self.videoTable)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.nameLbl.setToolTip(QtGui.QApplication.translate("MainWindow", "Video file name", None, QtGui.QApplication.UnicodeUTF8))
        self.nameLbl.setText(QtGui.QApplication.translate("MainWindow", "Video:", None, QtGui.QApplication.UnicodeUTF8))
        self.videoNameLlb.setText(QtGui.QApplication.translate("MainWindow", "video_name.avi", None, QtGui.QApplication.UnicodeUTF8))
        self.zoomLbl.setToolTip(QtGui.QApplication.translate("MainWindow", "Zoom in video", None, QtGui.QApplication.UnicodeUTF8))
        self.zoomLbl.setText(QtGui.QApplication.translate("MainWindow", "ZOOM:", None, QtGui.QApplication.UnicodeUTF8))
        self.zoomlSlider.setToolTip(QtGui.QApplication.translate("MainWindow", "Zoom in video", None, QtGui.QApplication.UnicodeUTF8))
        self.zoomValueLbl.setToolTip(QtGui.QApplication.translate("MainWindow", "Zoom in video", None, QtGui.QApplication.UnicodeUTF8))
        self.zoomValueLbl.setText(QtGui.QApplication.translate("MainWindow", "100%", None, QtGui.QApplication.UnicodeUTF8))
        self.userLbl.setText(QtGui.QApplication.translate("MainWindow", "user", None, QtGui.QApplication.UnicodeUTF8))
        self.rectToolBtn.setToolTip(QtGui.QApplication.translate("MainWindow", "Add rectangle [Alt+R]", None, QtGui.QApplication.UnicodeUTF8))
        self.rectToolBtn.setShortcut(QtGui.QApplication.translate("MainWindow", "Alt+R", None, QtGui.QApplication.UnicodeUTF8))
        self.circleToolBtn.setToolTip(QtGui.QApplication.translate("MainWindow", "Add circle [Alt+C]", None, QtGui.QApplication.UnicodeUTF8))
        self.circleToolBtn.setShortcut(QtGui.QApplication.translate("MainWindow", "Alt+C", None, QtGui.QApplication.UnicodeUTF8))
        self.ellipseToolBtn.setToolTip(QtGui.QApplication.translate("MainWindow", "Add ellipse [Alt+E]", None, QtGui.QApplication.UnicodeUTF8))
        self.ellipseToolBtn.setShortcut(QtGui.QApplication.translate("MainWindow", "Alt+E", None, QtGui.QApplication.UnicodeUTF8))
        self.pointToolBtn.setToolTip(QtGui.QApplication.translate("MainWindow", "Add point [Alt+P]", None, QtGui.QApplication.UnicodeUTF8))
        self.pointToolBtn.setShortcut(QtGui.QApplication.translate("MainWindow", "Alt+P", None, QtGui.QApplication.UnicodeUTF8))
        self.nonVisToolBtn.setToolTip(QtGui.QApplication.translate("MainWindow", "Add non-visual annotation [Alt+N]", None, QtGui.QApplication.UnicodeUTF8))
        self.nonVisToolBtn.setShortcut(QtGui.QApplication.translate("MainWindow", "Alt+N", None, QtGui.QApplication.UnicodeUTF8))
        self.maskToolBtn.setToolTip(QtGui.QApplication.translate("MainWindow", "Add graphic mask", None, QtGui.QApplication.UnicodeUTF8))
        self.maskToolBtn.setShortcut(QtGui.QApplication.translate("MainWindow", "Alt+M", None, QtGui.QApplication.UnicodeUTF8))
        self.toolsAndVideoTabWidget.setTabText(self.toolsAndVideoTabWidget.indexOf(self.toolsTab), QtGui.QApplication.translate("MainWindow", "Annotation tools", None, QtGui.QApplication.UnicodeUTF8))
        self.annotationsTable.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "Description", None, QtGui.QApplication.UnicodeUTF8))
        self.annotationsTable.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "Type", None, QtGui.QApplication.UnicodeUTF8))
        self.annotationsTable.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "id", None, QtGui.QApplication.UnicodeUTF8))
        self.toolsAndVideoTabWidget.setTabText(self.toolsAndVideoTabWidget.indexOf(self.annotationsTab), QtGui.QApplication.translate("MainWindow", "Annotations", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.videoTable.isSortingEnabled()
        self.videoTable.setSortingEnabled(False)
        self.videoTable.item(0, 0).setText(QtGui.QApplication.translate("MainWindow", "Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.videoTable.item(1, 0).setText(QtGui.QApplication.translate("MainWindow", "Filename:", None, QtGui.QApplication.UnicodeUTF8))
        self.videoTable.item(2, 0).setText(QtGui.QApplication.translate("MainWindow", "Resolution:", None, QtGui.QApplication.UnicodeUTF8))
        self.videoTable.item(3, 0).setText(QtGui.QApplication.translate("MainWindow", "FPS:", None, QtGui.QApplication.UnicodeUTF8))
        self.videoTable.item(4, 0).setText(QtGui.QApplication.translate("MainWindow", "Duration:", None, QtGui.QApplication.UnicodeUTF8))
        self.videoTable.item(5, 0).setText(QtGui.QApplication.translate("MainWindow", "Active:", None, QtGui.QApplication.UnicodeUTF8))
        self.videoTable.setSortingEnabled(__sortingEnabled)
        self.toolsAndVideoTabWidget.setTabText(self.toolsAndVideoTabWidget.indexOf(self.videoTab), QtGui.QApplication.translate("MainWindow", "Video", None, QtGui.QApplication.UnicodeUTF8))
        self.annotAttributesLbl.setText(QtGui.QApplication.translate("MainWindow", "Annotation attributes:", None, QtGui.QApplication.UnicodeUTF8))
        self.globalTable.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "Global", None, QtGui.QApplication.UnicodeUTF8))
        self.globalTable.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "Value", None, QtGui.QApplication.UnicodeUTF8))
        self.localTable.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "Local", None, QtGui.QApplication.UnicodeUTF8))
        self.localTable.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "Value", None, QtGui.QApplication.UnicodeUTF8))
        self.skipLeftBtn.setToolTip(QtGui.QApplication.translate("MainWindow", "Jump backward to nearest annotation [Ctrl+Down]", None, QtGui.QApplication.UnicodeUTF8))
        self.skipLeftBtn.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Down", None, QtGui.QApplication.UnicodeUTF8))
        self.skipSecBackBtn.setToolTip(QtGui.QApplication.translate("MainWindow", "Seek one second backward [Ctrl+Left]", None, QtGui.QApplication.UnicodeUTF8))
        self.skipSecBackBtn.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Left", None, QtGui.QApplication.UnicodeUTF8))
        self.frameLeftBtn.setToolTip(QtGui.QApplication.translate("MainWindow", "Seek one frame backward [Left]", None, QtGui.QApplication.UnicodeUTF8))
        self.frameLeftBtn.setShortcut(QtGui.QApplication.translate("MainWindow", "Left", None, QtGui.QApplication.UnicodeUTF8))
        self.playPauseBtn.setToolTip(QtGui.QApplication.translate("MainWindow", "Play/Pause the video [Space]", None, QtGui.QApplication.UnicodeUTF8))
        self.stopBtn.setToolTip(QtGui.QApplication.translate("MainWindow", "Stop the video", None, QtGui.QApplication.UnicodeUTF8))
        self.frameRightBtn.setToolTip(QtGui.QApplication.translate("MainWindow", "Seek one frame forward [Right]", None, QtGui.QApplication.UnicodeUTF8))
        self.frameRightBtn.setShortcut(QtGui.QApplication.translate("MainWindow", "Right", None, QtGui.QApplication.UnicodeUTF8))
        self.skipSecFwdBtn.setToolTip(QtGui.QApplication.translate("MainWindow", "Seek one second forward [Ctrl+Right]", None, QtGui.QApplication.UnicodeUTF8))
        self.skipSecFwdBtn.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Right", None, QtGui.QApplication.UnicodeUTF8))
        self.skipRightBtn.setToolTip(QtGui.QApplication.translate("MainWindow", "Jump forward to nearest annotation [Ctrl+Up]", None, QtGui.QApplication.UnicodeUTF8))
        self.skipRightBtn.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Up", None, QtGui.QApplication.UnicodeUTF8))
        self.timeLbl.setToolTip(QtGui.QApplication.translate("MainWindow", "Current time", None, QtGui.QApplication.UnicodeUTF8))
        self.timeLbl.setText(QtGui.QApplication.translate("MainWindow", "00:00:00:00", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Precise seek: ", None, QtGui.QApplication.UnicodeUTF8))
        self.perFrameSlider.setToolTip(QtGui.QApplication.translate("MainWindow", "Presice video seeking", None, QtGui.QApplication.UnicodeUTF8))
        self.undoBtn.setToolTip(QtGui.QApplication.translate("MainWindow", "Revert all changes sice last save [Ctrl+Z]", None, QtGui.QApplication.UnicodeUTF8))
        self.commitBtn.setToolTip(QtGui.QApplication.translate("MainWindow", "Save all changes to database [Ctrl+S]", None, QtGui.QApplication.UnicodeUTF8))
        self.commitBtn.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuTools.setTitle(QtGui.QApplication.translate("MainWindow", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.menuView.setTitle(QtGui.QApplication.translate("MainWindow", "View", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFont_size.setTitle(QtGui.QApplication.translate("MainWindow", "Font size", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClose.setText(QtGui.QApplication.translate("MainWindow", "Close", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClose.setToolTip(QtGui.QApplication.translate("MainWindow", "Close the program", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClose.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUndo_changes.setText(QtGui.QApplication.translate("MainWindow", "Undo changes", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUndo_changes.setToolTip(QtGui.QApplication.translate("MainWindow", "Undo all changes since last changes", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUndo_changes.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Z", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCommit.setText(QtGui.QApplication.translate("MainWindow", "Save changes", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCommit.setToolTip(QtGui.QApplication.translate("MainWindow", "Save all changes", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCommit.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+S", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDelete.setText(QtGui.QApplication.translate("MainWindow", "Delete object", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDelete.setShortcut(QtGui.QApplication.translate("MainWindow", "Shift+Del", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTake_a_snapshot.setText(QtGui.QApplication.translate("MainWindow", "Take a snapshot", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFit_to_video.setText(QtGui.QApplication.translate("MainWindow", "Fit to video", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFontSmall.setText(QtGui.QApplication.translate("MainWindow", "Small", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFontNormal.setText(QtGui.QApplication.translate("MainWindow", "Normal", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFontLarge.setText(QtGui.QApplication.translate("MainWindow", "Large", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFontNone.setText(QtGui.QApplication.translate("MainWindow", "None", None, QtGui.QApplication.UnicodeUTF8))
        self.actionKeyboard_shortcuts.setText(QtGui.QApplication.translate("MainWindow", "Keyboard shortcuts", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGo_to.setText(QtGui.QApplication.translate("MainWindow", "Go to", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGo_to.setIconText(QtGui.QApplication.translate("MainWindow", "Go to frame/time", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGo_to.setToolTip(QtGui.QApplication.translate("MainWindow", "Go to frame/time", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGo_to.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+G", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMark_current_frame.setText(QtGui.QApplication.translate("MainWindow", "Mark current frame", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMark_current_frame.setIconText(QtGui.QApplication.translate("MainWindow", "Memory current video position", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMark_current_frame.setToolTip(QtGui.QApplication.translate("MainWindow", "Memory current video position", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMark_current_frame.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+M", None, QtGui.QApplication.UnicodeUTF8))

import icons_rc
