# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uic_files\mask.ui'
#
# Created: Thu Dec 12 10:44:54 2013
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_maskForm(object):
    def setupUi(self, maskForm):
        maskForm.setObjectName("maskForm")
        maskForm.resize(627, 408)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/app_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        maskForm.setWindowIcon(icon)
        maskForm.setSizeGripEnabled(True)
        self.verticalLayout = QtGui.QVBoxLayout(maskForm)
        self.verticalLayout.setObjectName("verticalLayout")
        self.toolbarLayout = QtGui.QHBoxLayout()
        self.toolbarLayout.setObjectName("toolbarLayout")
        self.brushTypeLbl = QtGui.QLabel(maskForm)
        self.brushTypeLbl.setObjectName("brushTypeLbl")
        self.toolbarLayout.addWidget(self.brushTypeLbl)
        self.brushTypeCombo = QtGui.QComboBox(maskForm)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.brushTypeCombo.sizePolicy().hasHeightForWidth())
        self.brushTypeCombo.setSizePolicy(sizePolicy)
        self.brushTypeCombo.setObjectName("brushTypeCombo")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/rectangle.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.brushTypeCombo.addItem(icon1, "")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/circle.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.brushTypeCombo.addItem(icon2, "")
        self.toolbarLayout.addWidget(self.brushTypeCombo)
        self.opacityLbl = QtGui.QLabel(maskForm)
        self.opacityLbl.setObjectName("opacityLbl")
        self.toolbarLayout.addWidget(self.opacityLbl)
        self.opacityEdit = QtGui.QLineEdit(maskForm)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.opacityEdit.sizePolicy().hasHeightForWidth())
        self.opacityEdit.setSizePolicy(sizePolicy)
        self.opacityEdit.setMaximumSize(QtCore.QSize(30, 16777215))
        self.opacityEdit.setObjectName("opacityEdit")
        self.toolbarLayout.addWidget(self.opacityEdit)
        self.sizeLbl = QtGui.QLabel(maskForm)
        self.sizeLbl.setObjectName("sizeLbl")
        self.toolbarLayout.addWidget(self.sizeLbl)
        self.sizeEdit = QtGui.QLineEdit(maskForm)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sizeEdit.sizePolicy().hasHeightForWidth())
        self.sizeEdit.setSizePolicy(sizePolicy)
        self.sizeEdit.setMaximumSize(QtCore.QSize(30, 16777215))
        self.sizeEdit.setObjectName("sizeEdit")
        self.toolbarLayout.addWidget(self.sizeEdit)
        self.hideBgrCheck = QtGui.QCheckBox(maskForm)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hideBgrCheck.sizePolicy().hasHeightForWidth())
        self.hideBgrCheck.setSizePolicy(sizePolicy)
        self.hideBgrCheck.setObjectName("hideBgrCheck")
        self.toolbarLayout.addWidget(self.hideBgrCheck)
        self.saveBtn = QtGui.QPushButton(maskForm)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.saveBtn.sizePolicy().hasHeightForWidth())
        self.saveBtn.setSizePolicy(sizePolicy)
        self.saveBtn.setMinimumSize(QtCore.QSize(0, 30))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/save_mask.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.saveBtn.setIcon(icon3)
        self.saveBtn.setIconSize(QtCore.QSize(20, 20))
        self.saveBtn.setAutoDefault(False)
        self.saveBtn.setObjectName("saveBtn")
        self.toolbarLayout.addWidget(self.saveBtn)
        self.verticalLayout.addLayout(self.toolbarLayout)
        self.graphicsView = QtGui.QGraphicsView(maskForm)
        self.graphicsView.setObjectName("graphicsView")
        self.verticalLayout.addWidget(self.graphicsView)

        self.retranslateUi(maskForm)
        QtCore.QMetaObject.connectSlotsByName(maskForm)

    def retranslateUi(self, maskForm):
        maskForm.setWindowTitle(QtGui.QApplication.translate("maskForm", "Annotation mask editor", None, QtGui.QApplication.UnicodeUTF8))
        self.brushTypeLbl.setText(QtGui.QApplication.translate("maskForm", "Brush:", None, QtGui.QApplication.UnicodeUTF8))
        self.brushTypeCombo.setToolTip(QtGui.QApplication.translate("maskForm", "Pick a brush type", None, QtGui.QApplication.UnicodeUTF8))
        self.brushTypeCombo.setItemText(0, QtGui.QApplication.translate("maskForm", "Rectangle", None, QtGui.QApplication.UnicodeUTF8))
        self.brushTypeCombo.setItemText(1, QtGui.QApplication.translate("maskForm", "Circle", None, QtGui.QApplication.UnicodeUTF8))
        self.opacityLbl.setText(QtGui.QApplication.translate("maskForm", "Opacity:", None, QtGui.QApplication.UnicodeUTF8))
        self.sizeLbl.setText(QtGui.QApplication.translate("maskForm", "Size:", None, QtGui.QApplication.UnicodeUTF8))
        self.hideBgrCheck.setToolTip(QtGui.QApplication.translate("maskForm", "Hides background image [Ctrl+H]", None, QtGui.QApplication.UnicodeUTF8))
        self.hideBgrCheck.setText(QtGui.QApplication.translate("maskForm", "Hide background", None, QtGui.QApplication.UnicodeUTF8))
        self.hideBgrCheck.setShortcut(QtGui.QApplication.translate("maskForm", "Ctrl+H", None, QtGui.QApplication.UnicodeUTF8))
        self.saveBtn.setToolTip(QtGui.QApplication.translate("maskForm", "Save mask [Ctrl+S]", None, QtGui.QApplication.UnicodeUTF8))
        self.saveBtn.setText(QtGui.QApplication.translate("maskForm", "Save and close", None, QtGui.QApplication.UnicodeUTF8))
        self.saveBtn.setShortcut(QtGui.QApplication.translate("maskForm", "Ctrl+S", None, QtGui.QApplication.UnicodeUTF8))

import icons_rc
